# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunctionList_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FunctionList_Swift

pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'ReachabilitySwift'
pod 'GoogleSignIn'
pod 'Firebase/DynamicLinks'


end
